# ============================================
# Terraform Hands-On Tutorial
# ============================================
# This project teaches core Terraform concepts
# using local providers (no cloud account needed)
# ============================================

terraform {
  required_version = ">= 1.0"

  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
  }
}

# ============================================
# VARIABLES - Input values for reusability
# ============================================

variable "environment" {
  type        = string
  default     = "dev"
  description = "Environment name (dev, staging, prod)"
}

variable "app_name" {
  type        = string
  default     = "myapp"
  description = "Application name"
}

variable "config_options" {
  type = object({
    debug_mode = bool
    log_level  = string
    port       = number
  })
  default = {
    debug_mode = true
    log_level  = "info"
    port       = 8080
  }
  description = "Application configuration options"
}

# ============================================
# LOCALS - Computed values
# ============================================

locals {
  # Combine variables into useful values
  full_name   = "${var.app_name}-${var.environment}"
  output_dir  = "${path.module}/output"

  # Conditional logic
  is_prod     = var.environment == "prod"
  log_level   = local.is_prod ? "warn" : var.config_options.log_level
}

# ============================================
# RESOURCES - Things Terraform creates
# ============================================

# Generate a random ID (simulates creating a unique resource)
resource "random_id" "app_id" {
  byte_length = 4
  prefix      = "${local.full_name}-"
}

# Generate a random password (common real-world use case)
resource "random_password" "db_password" {
  length  = 16
  special = true
}

# Create a local file (simulates deploying a config)
resource "local_file" "app_config" {
  filename = "${local.output_dir}/config.json"
  content = jsonencode({
    app_id      = random_id.app_id.hex
    environment = var.environment
    debug       = var.config_options.debug_mode
    log_level   = local.log_level
    port        = var.config_options.port
    created_at  = timestamp()
  })

  # File permissions (Unix style)
  file_permission = "0644"
}

# ============================================
# MULTIPLE RESOURCES WITH COUNT
# ============================================

variable "services" {
  type    = list(string)
  default = ["api", "web", "worker"]
}

# Create a config file for each service
resource "local_file" "service_configs" {
  count    = length(var.services)
  filename = "${local.output_dir}/services/${var.services[count.index]}.json"
  content = jsonencode({
    service     = var.services[count.index]
    environment = var.environment
    app_id      = random_id.app_id.hex
    port        = 8080 + count.index
  })
}

# Create another file using a template
resource "local_file" "env_file" {
  filename = "${local.output_dir}/.env"
  content  = <<-EOT
    # Generated by Terraform - do not edit manually
    APP_NAME=${var.app_name}
    ENVIRONMENT=${var.environment}
    APP_ID=${random_id.app_id.hex}
    DB_PASSWORD=${random_password.db_password.result}
    PORT=${var.config_options.port}
    DEBUG=${var.config_options.debug_mode}
  EOT

  file_permission = "0600"  # Restrictive since it has secrets
}

# ============================================
# MULTIPLE RESOURCES WITH FOR_EACH
# ============================================

variable "databases" {
  type = map(object({
    engine = string
    port   = number
  }))
  default = {
    "users" = { engine = "postgres", port = 5432 }
    "cache" = { engine = "redis", port = 6379 }
    "logs"  = { engine = "elasticsearch", port = 9200 }
  }
}

# Create a config for each database
resource "local_file" "db_configs" {
  for_each = var.databases
  filename = "${local.output_dir}/databases/${each.key}.json"
  content = jsonencode({
    name        = each.key
    engine      = each.value.engine
    port        = each.value.port
    environment = var.environment
  })
}

# ============================================
# OUTPUTS - Values to display/export
# ============================================

output "app_id" {
  value       = random_id.app_id.hex
  description = "The generated application ID"
}

output "config_file" {
  value       = local_file.app_config.filename
  description = "Path to the generated config file"
}

output "env_file" {
  value       = local_file.env_file.filename
  description = "Path to the generated .env file"
}

# Sensitive outputs are hidden in CLI output
output "db_password" {
  value       = random_password.db_password.result
  sensitive   = true
  description = "The generated database password"
}

output "service_configs" {
  value       = [for f in local_file.service_configs : f.filename]
  description = "Paths to service config files (created with count)"
}

output "db_configs" {
  value       = { for k, f in local_file.db_configs : k => f.filename }
  description = "Paths to database config files (created with for_each)"
}

output "summary" {
  value = <<-EOT

    ✓ Application: ${local.full_name}
    ✓ App ID:      ${random_id.app_id.hex}
    ✓ Environment: ${var.environment}
    ✓ Services:    ${join(", ", var.services)}
    ✓ Databases:   ${join(", ", keys(var.databases))}
  EOT
}
